Repository lazygpt/lazygpt, pull requests merged in 2023-04, with the labels that each got.

#8 feat(readme): add basic readme
  README.md
Labels: codeball:needs-review

#13 feat(plugin): add log helpers
  Makefile
  cmd/lazygpt/app/chat.go
  cmd/lazygpt/app/root.go
  cmd/lazygpt/lazygpt.go
  pkg/plugin/client.go
  plugin/api/completion.go
  plugin/api/interfaces.go
  plugin/api/logging.go
  plugin/log/context.go
  plugin/log/log.go
  plugin/openai/pkg/openai/openai.go
Labels: codeball:approved

#14 feat(embedding): add embedding interface
  plugin/api/api.go
  plugin/api/embedding.go
  plugin/api/interfaces.proto
  plugin/openai/cmd/main.go
  plugin/openai/pkg/openai/openai.go
Labels: codeball:needs-review

#15 chore(plugins): dry up plugin scaffolding
  plugin/api/api.go
  plugin/api/completion.go
  plugin/api/embedding.go
  plugin/api/interfaces.go
  plugin/api/plugin.go
Labels: codeball:approved

#16 feat(make): makefile documentation
  Makefile
Labels: codeball:needs-review

#17 feat(memory): add memory interface
  .github/dependabot.yaml
  Makefile
  cmd/lazygpt/app/chat.go
  go.mod
  go.sum
  pkg/tokens/counter.go
  pkg/tokens/counter_test.go
  plugin/api/api.go
  plugin/api/completion.go
  plugin/api/interfaces.proto
  plugin/api/memory.go
  plugin/api/plugin.go
  plugin/local/cmd/main.go
  plugin/local/go.mod
  plugin/local/go.sum
  plugin/local/pkg/local/local.go
  plugin/local/pkg/memory/closest.go
  plugin/local/pkg/memory/closest_test.go
  plugin/local/pkg/memory/local.go
  plugin/local/pkg/memory/log.go
  plugin/log/log.go
Labels: codeball:needs-careful-review

#22 fix(chat): fix context calulation
  cmd/lazygpt/app/chat.go
  cmd/lazygpt/app/root.go
  plugin/log/log.go
Labels: codeball:approved
